language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install --no-interaction
  - composer self-update
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/rainlab/user
  - mv !(october) october/plugins/rainlab/user
  - cd october
  - git clone https://github.com/rainlab/notify-plugin.git ./plugins/rainlab/notify
  - composer install
  - cp config/cms.php config/cms.php.testing
  - mv config/cms.php.testing config/testing/cms.php
  - cd plugins/rainlab/user
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover=clover.xml